### ISSUE TITLE
Add incidence data

### ISSUE THREAD

**Issue by timcdlucas** [aknandi/TMBworkshop#6]
Requires chosing a sensible area.

https://datadryad.org/bitstream/handle/10255/dryad.82194/PfPvAllData01042015_AgeStand.csv?sequence=1

**Comment by aknandi** [comment]
Included in https://github.com/aknandi/TMBworkshop/commit/89c1630fbcbfb87052dc1389f057321434dc59d3 

Chosen to use Kenya: 1614 prevalence points and 124 incidence points
